name: CI/CD
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-dependencies
        run: yarn install

      - name: web build
        run: yarn build
